--
-- Table structure for table `langs`
--

CREATE TABLE `langs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `native_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `iso_639_1` char(2) NOT NULL,
  `iso_639_2` char(3) NOT NULL,
  `enable` tinyint(1) NOT NULL DEFAULT 0,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `langs`
--

INSERT INTO `langs` (`id`, `native_name`, `iso_639_1`, `iso_639_2`) VALUES
(1, 'аҧсуа бызшәа, аҧсшәа', 'ab', 'abk'),
(2, 'Afaraf', 'aa', 'aar'),
(3, 'Afrikaans', 'af', 'afr'),
(4, 'Akan', 'ak', 'aka'),
(5, 'Shqip', 'sq', 'alb'),
(6, 'አማርኛ', 'am', 'amh'),
(7, 'العربية', 'ar', 'ara'),
(8, 'aragonés', 'an', 'arg'),
(9, 'Հայերեն', 'hy', 'arm'),
(10, 'অসমীয়া', 'as', 'asm'),
(11, 'авар мацӀ, магӀарул мацӀ', 'av', 'ava'),
(12, 'avesta', 'ae', 'ave'),
(13, 'aymar aru', 'ay', 'aym'),
(14, 'azərbaycan dili, تۆرکجه', 'az', 'aze'),
(15, 'bamanankan', 'bm', 'bam'),
(16, 'башҡорт теле', 'ba', 'bak'),
(17, 'euskara, euskera', 'eu', 'baq'),
(18, 'беларуская мова', 'be', 'bel'),
(19, 'বাংলা', 'bn', 'ben'),
(20, 'Bislama', 'bi', 'bis'),
(21, 'bosanski jezik', 'bs', 'bos'),
(22, 'brezhoneg', 'br', 'bre'),
(23, 'български език', 'bg', 'bul'),
(24, 'ဗမာစာ', 'my', 'bur'),
(25, 'català, valencià', 'ca', 'cat'),
(26, 'Chamoru', 'ch', 'cha'),
(27, 'нохчийн мотт', 'ce', 'che'),
(28, 'chiCheŵa, chinyanja', 'ny', 'nya'),
(29, '中文 (Zhōngwén), 汉语, 漢語', 'zh', 'chi'),
(30, 'чӑваш чӗлхи', 'cv', 'chv'),
(31, 'Kernewek', 'kw', 'cor'),
(32, 'corsu, lingua corsa', 'co', 'cos'),
(33, 'ᓀᐦᐃᔭᐍᐏᐣ', 'cr', 'cre'),
(34, 'hrvatski jezik', 'hr', 'hrv'),
(35, 'čeština, český jazyk', 'cs', 'cze'),
(36, 'dansk', 'da', 'dan'),
(37, 'ދިވެހި', 'dv', 'div'),
(38, 'Nederlands, Vlaams', 'nl', 'dut'),
(39, 'རྫོང་ཁ', 'dz', 'dzo'),
(40, 'English', 'en', 'eng'),
(41, 'Esperanto', 'eo', 'epo'),
(42, 'eesti, eesti keel', 'et', 'est'),
(43, 'Eʋegbe', 'ee', 'ewe'),
(44, 'føroyskt', 'fo', 'fao'),
(45, 'vosa Vakaviti', 'fj', 'fij'),
(46, 'suomi, suomen kieli', 'fi', 'fin'),
(47, 'français', 'fr', 'fre'),
(48, 'Fulfulde, Pulaar, Pular', 'ff', 'ful'),
(49, 'Galego', 'gl', 'glg'),
(50, 'ქართული', 'ka', 'geo'),
(51, 'Deutsch', 'de', 'ger'),
(52, 'Ελληνικά', 'el', 'gre'),
(53, 'Avañe\'ẽ', 'gn', 'grn'),
(54, 'ગુજરાતી', 'gu', 'guj'),
(55, 'Kreyòl ayisyen', 'ht', 'hat'),
(56, '(Hausa) هَوُسَ', 'ha', 'hau'),
(57, 'עברית', 'he', 'heb'),
(58, 'Otjiherero', 'hz', 'her'),
(59, 'हिन्दी, हिंदी', 'hi', 'hin'),
(60, 'Hiri Motu', 'ho', 'hmo'),
(61, 'magyar', 'hu', 'hun'),
(62, 'Interlingua', 'ia', 'ina'),
(63, 'Bahasa Indonesia', 'id', 'ind'),
(64, '(originally:) Occidental, (after WWII:) Interlingu', 'ie', 'ile'),
(65, 'Gaeilge', 'ga', 'gle'),
(66, 'Asụsụ Igbo', 'ig', 'ibo'),
(67, 'Iñupiaq, Iñupiatun', 'ik', 'ipk'),
(68, 'Ido', 'io', 'ido'),
(69, 'Íslenska', 'is', 'ice'),
(70, 'Italiano', 'it', 'ita'),
(71, 'ᐃᓄᒃᑎᑐᑦ', 'iu', 'iku'),
(72, '日本語 (にほんご)', 'ja', 'jpn'),
(73, 'ꦧꦱꦗꦮ, Basa Jawa', 'jv', 'jav'),
(74, 'kalaallisut, kalaallit oqaasii', 'kl', 'kal'),
(75, 'ಕನ್ನಡ', 'kn', 'kan'),
(76, 'Kanuri', 'kr', 'kau'),
(77, 'कॉशुर, کٲشُر', 'ks', 'kas'),
(78, 'қазақ тілі', 'kk', 'kaz'),
(79, 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', 'km', 'khm'),
(80, 'Gĩkũyũ', 'ki', 'kik'),
(81, 'Ikinyarwanda', 'rw', 'kin'),
(82, 'Кыргызча, Кыргыз тили', 'ky', 'kir'),
(83, 'коми кыв', 'kv', 'kom'),
(84, 'Kikongo', 'kg', 'kon'),
(85, '한국어', 'ko', 'kor'),
(86, 'Kurdî, کوردی', 'ku', 'kur'),
(87, 'Kuanyama', 'kj', 'kua'),
(88, 'latine, lingua latina', 'la', 'lat'),
(89, 'Lëtzebuergesch', 'lb', 'ltz'),
(90, 'Luganda', 'lg', 'lug'),
(91, 'Limburgs', 'li', 'lim'),
(92, 'Lingála', 'ln', 'lin'),
(93, 'ພາສາລາວ', 'lo', 'lao'),
(94, 'lietuvių kalba', 'lt', 'lit'),
(95, 'Kiluba', 'lu', 'lub'),
(96, 'latviešu valoda', 'lv', 'lav'),
(97, 'Gaelg, Gailck', 'gv', 'glv'),
(98, 'македонски јазик', 'mk', 'mac'),
(99, 'fiteny malagasy', 'mg', 'mlg'),
(100, 'Bahasa Melayu, بهاس ملايو', 'ms', 'may'),
(101, 'മലയാളം', 'ml', 'mal'),
(102, 'Malti', 'mt', 'mlt'),
(103, 'te reo Māori', 'mi', 'mao'),
(104, 'मराठी', 'mr', 'mar'),
(105, 'Kajin M̧ajeļ', 'mh', 'mah'),
(106, 'Монгол хэл', 'mn', 'mon'),
(107, 'Dorerin Naoero', 'na', 'nau'),
(108, 'Diné bizaad', 'nv', 'nav'),
(109, 'isiNdebele', 'nd', 'nde'),
(110, 'नेपाली', 'ne', 'nep'),
(111, 'Owambo', 'ng', 'ndo'),
(112, 'Norsk Bokmål', 'nb', 'nob'),
(113, 'Norsk Nynorsk', 'nn', 'nno'),
(114, 'Norsk', 'no', 'nor'),
(115, 'ꆈꌠ꒿ Nuosuhxop', 'ii', 'iii'),
(116, 'isiNdebele', 'nr', 'nbl'),
(117, 'occitan, lenga d\'òc', 'oc', 'oci'),
(118, 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'oj', 'oji'),
(119, 'ѩзыкъ словѣньскъ', 'cu', 'chu'),
(120, 'Afaan Oromoo', 'om', 'orm'),
(121, 'ଓଡ଼ିଆ', 'or', 'ori'),
(122, 'ирон ӕвзаг', 'os', 'oss'),
(123, 'ਪੰਜਾਬੀ, پنجابی', 'pa', 'pan'),
(124, 'पालि, पाळि', 'pi', 'pli'),
(125, 'فارسی', 'fa', 'per'),
(126, 'język polski, polszczyzna', 'pl', 'pol'),
(127, 'پښتو', 'ps', 'pus'),
(128, 'Português', 'pt', 'por'),
(129, 'Runa Simi, Kichwa', 'qu', 'que'),
(130, 'Rumantsch Grischun', 'rm', 'roh'),
(131, 'Ikirundi', 'rn', 'run'),
(132, 'Română, Moldovenească', 'ro', 'rum'),
(133, 'русский', 'ru', 'rus'),
(134, 'संस्कृतम्, 𑌸𑌂𑌸𑍍𑌕𑍃𑌤𑌮𑍍', 'sa', 'san'),
(135, 'sardu', 'sc', 'srd'),
(136, 'सिंधी, سنڌي', 'sd', 'snd'),
(137, 'Davvisámegiella', 'se', 'sme'),
(138, 'gagana fa\'a Samoa', 'sm', 'smo'),
(139, 'yângâ tî sängö', 'sg', 'sag'),
(140, 'српски језик', 'sr', 'srp'),
(141, 'Gàidhlig', 'gd', 'gla'),
(142, 'chiShona', 'sn', 'sna'),
(143, 'සිංහල', 'si', 'sin'),
(144, 'slovenčina, slovenský jazyk', 'sk', 'slo'),
(145, 'Slovenski jezik, Slovenščina', 'sl', 'slv'),
(146, 'Soomaaliga, af Soomaali', 'so', 'som'),
(147, 'Sesotho', 'st', 'sot'),
(148, 'Español', 'es', 'spa'),
(149, 'Basa Sunda', 'su', 'sun'),
(150, 'Kiswahili', 'sw', 'swa'),
(151, 'SiSwati', 'ss', 'ssw'),
(152, 'Svenska', 'sv', 'swe'),
(153, 'தமிழ்', 'ta', 'tam'),
(154, 'తెలుగు', 'te', 'tel'),
(155, 'тоҷикӣ, toçikī, تاجیکی', 'tg', 'tgk'),
(156, 'ไทย', 'th', 'tha'),
(157, 'ትግርኛ', 'ti', 'tir'),
(158, 'བོད་ཡིག', 'bo', 'tib'),
(159, 'Türkmençe, Türkmen dili', 'tk', 'tuk'),
(160, 'Wikang Tagalog', 'tl', 'tgl'),
(161, 'Setswana', 'tn', 'tsn'),
(162, 'Faka Tonga', 'to', 'ton'),
(163, 'Türkçe', 'tr', 'tur'),
(164, 'Xitsonga', 'ts', 'tso'),
(165, 'татар теле, tatar tele', 'tt', 'tat'),
(166, 'Twi', 'tw', 'twi'),
(167, 'Reo Tahiti', 'ty', 'tah'),
(168, 'ئۇيغۇرچە, Uyghurche', 'ug', 'uig'),
(169, 'Українська', 'uk', 'ukr'),
(170, 'اردو', 'ur', 'urd'),
(171, 'Oʻzbek, Ўзбек, أۇزبېك', 'uz', 'uzb'),
(172, 'Tshivenḓa', 've', 'ven'),
(173, 'Tiếng Việt', 'vi', 'vie'),
(174, 'Volapük', 'vo', 'vol'),
(175, 'Walon', 'wa', 'wln'),
(176, 'Cymraeg', 'cy', 'wel'),
(177, 'Wollof', 'wo', 'wol'),
(178, 'Frysk', 'fy', 'fry'),
(179, 'isiXhosa', 'xh', 'xho'),
(180, 'ייִדיש', 'yi', 'yid'),
(181, 'Yorùbá', 'yo', 'yor'),
(182, 'Saɯ cueŋƅ, Saw cuengh', 'za', 'zha'),
(183, 'isiZulu', 'zu', 'zul');

--
-- Indexes for table `langs`
--
ALTER TABLE `langs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `langs`
--
ALTER TABLE `langs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=184;